### PR TITLE
Feature: #2 Save to/Open from Journal

### PR DESCRIPTION
**Pull request by rhl-bthr**
**Feature added in this PR:** #2

**Features:**
 1. User can click on save to journal and the current file will be saved as a journal activity instance
 2. Gives the activity instance the same name as the file name

**Note:** The current file should already be saved in the filesystem

**Tested on:**
Sugar 0.112. packaged environment (rdesktop). Ubuntu 16.04

@cristian99garcia, kindly review

### CODE REVIEW

**Comment by cvgarciarea** [comment]
It works for me, but it doesn't what I had in mind (sorry for little specific descriptions).
I thought about a button on File with some label like "Export file to the Journal" (something like "Save as"). Once the user save a file on its Journal, it will be able to use "Save" button to save modifications.
I know, we will have many save and open toolbuttons, probably implementing something like this (from turtleblocks) would be great:
a screenshot here

And for opening/saving(? files from/to Journal (actually I don't know if this file chooser can be used to save files) we should use sugar ObjectChooser:
another screenshot

**Comment by rhl-bthr** [comment]
Apologies for misunderstanding your idea.

Along with my exisiting PR, can I add a feature to store unsaved files as journal instances as well ?
This will incorporate all the above mentioned features as well.

**Comment by cvgarciarea** [comment]
@Pro-Panda I really don't think it's a good idea because CEdit can have many open files at the same time, so one CEdit Journal instance must be able to refers to all these files.

Summarizing:
- If the user clicks on "Save to Journal", the activity must create a Journal instance for that file.
- If the user closes the activity with saved/unsaved files, the CEdit Journal instance will be refer to all these files like a project (already done, thanks for that!).

**Comment by Pro-Panda** [comment]
@cristian99garcia, great. 
Thank you for the explanation 😄 
I'll modify my changes accordingly

**Comment by Pro-Panda** [comment]
Clsoing, since it still requires some discussion with @cristian99garcia

**Pull request closed without merging**
